### ISSUE TITLE
Observed once: Access to the path 'minion.pem' is denied.

### ISSUE THREAD

**Issue by marbx** [marbx/salt-windows-msi#33]
```
MSI (s) (E4:48) [09:45:01:150]: Executing op: FolderRemove(Folder=C:\salt\conf\pki\minion\,Foreign=0)
MSI (s) (E4:48) [09:45:01:150]: Note: 1: 2318 2:  
MSI (s) (E4:48) [09:45:01:150]: Executing op: FolderRemove(Folder=C:\salt\var\cache\,Foreign=0)
MSI (s) (E4:48) [09:45:01:150]: Executing op: FolderRemove(Folder=C:\salt\var\cache\salt\,Foreign=0)
MSI (s) (E4:48) [09:45:01:150]: Executing op: FolderRemove(Folder=C:\salt\var\cache\salt\minion\,Foreign=0)
MSI (s) (E4:48) [09:45:01:150]: Executing op: FolderRemove(Folder=C:\salt\var\cache\salt\minion\extmods\,Foreign=0)
MSI (s) (E4:48) [09:45:01:150]: Executing op: FolderRemove(Folder=C:\salt\var\cache\salt\minion\extmods\grains\,Foreign=0)
MSI (s) (E4:48) [09:45:01:150]: Executing op: FolderRemove(Folder=C:\salt\var\cache\salt\minion\proc\,Foreign=0)
MSI (s) (E4:48) [09:45:01:150]: Executing op: FolderRemove(Folder=C:\salt\var\run\,Foreign=0)
MSI (s) (E4:48) [09:45:01:150]: Executing op: ActionStart(Name=MsiConfigureServices,,)
MSI (s) (E4:48) [09:45:01:150]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=1300000)
MSI (s) (E4:48) [09:45:01:150]: Executing op: ActionStart(Name=PublishProduct,Description=Publishing product information,)
MSI (s) (E4:48) [09:45:01:150]: Executing op: CleanupConfigData()
MSI (s) (E4:48) [09:45:01:150]: Executing op: RegisterPatchOrder(Continue=0,SequenceType=0,Remove=1)
MSI (s) (E4:48) [09:45:01:150]: Note: 1: 1402 2: UNKNOWN\Installer\Products\5EBBC40246441C84694A40C427B7A9A7\Patches 3: 2 
MSI (s) (E4:48) [09:45:01:150]: Executing op: RegisterPatchOrder(Continue=0,SequenceType=1,Remove=1)
MSI (s) (E4:48) [09:45:01:150]: Executing op: CleanupConfigData(RemovingProduct=1)
MSI (s) (E4:48) [09:45:01:150]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\UserData\S-1-5-18\Products\5EBBC40246441C84694A40C427B7A9A7\Patches 3: 2 
MSI (s) (E4:48) [09:45:01:150]: Executing op: End(Checksum=0,ProgressTotalHDWord=0,ProgressTotalLDWord=1956299400)
MSI (s) (E4:48) [09:45:01:150]: User policy value 'DisableRollback' is 0
MSI (s) (E4:48) [09:45:01:150]: Machine policy value 'DisableRollback' is 0
MSI (s) (E4:48) [09:45:07:873]: Note: 1: 2318 2:  
MSI (s) (E4:48) [09:45:08:326]: Note: 1: 2318 2:  
MSI (s) (E4:48) [09:45:08:326]: No System Restore sequence number for this installation.
MSI (s) (E4:48) [09:45:08:326]: Unlocking Server
MSI (s) (E4:48) [09:45:08:326]: PROPERTY CHANGE: Deleting UpdateStarted property. Its current value is '1'.
MSI (s) (E4:48) [09:45:08:326]: Doing action: CAC.NukeConf
Action ended 09:45:08: InstallFinalize. Return value 1.
MSI (s) (E4:18) [09:45:08:404]: Invoking remote custom action. DLL: C:\windows\Installer\MSI45FA.tmp, Entrypoint: CS_CUSTOM_ACTION_NUKE_CONF
Action start 09:45:08: CAC.NukeConf.
SFXCA: Extracting custom action to temporary directory: C:\windows\Installer\MSI45FA.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action MinionConfigurationExtension!MinionConfigurationExtension.MinionConfiguration.CS_CUSTOM_ACTION_NUKE_CONF
MinionConfiguration.cs:: Begin CS_CUSTOM_ACTION_NUKE_CONF
while deleting c:\salt\conf
Exception: Access to the path 'minion.pem' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at MinionConfigurationExtension.MinionConfiguration.CS_CUSTOM_ACTION_NUKE_CONF(Session session)
CustomAction CAC.NukeConf returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 09:45:09: CAC.NukeConf. Return value 3.
Action ended 09:45:09: INSTALL. Return value 3.
Property(S): UpgradeCode = {FC6FB3A2-65DE-41A9-AD91-D10A402BD641}
Property(S): BINFOLDER = C:\salt\bin\
Property(S): VARFOLDER = C:\salt\var\
Property(S): INSTALLFOLDER = C:\salt\


```

**Comment by marbx** [comment]
```
C:\git\salt-windows-msi>del C:\salt\conf\pki\minion\minion.pem
C:\salt\conf\pki\minion\minion.pem
Access is denied.
```
but

```
C:\git\salt-windows-msi>rmdir /s /q C:\salt\conf\
```
works

**Comment by markuskramerIgitt** [comment]
Fix issue after https://github.com/markuskramerIgitt/salt-windows-msi/issues/32

**Comment by marbx** [comment]
Permissions?

**Comment by marbx** [comment]
C# replaced by `on error resume next` [vbscript](https://github.com/markuskramerIgitt/salt-windows-msi/blob/c9be74be43fb7a86f0d69637c3734d3b7506a29b/wix.d/MinionMSI/Product.wxs#L110) in https://github.com/markuskramerIgitt/salt-windows-msi/commit/c9be74be43fb7a86f0d69637c3734d3b7506a29b

Probably same reason as https://github.com/markuskramerIgitt/salt-windows-msi/issues/40

**Comment by marbx** [comment]
Fixed by https://github.com/markuskramerIgitt/salt-windows-msi/commit/c9be74be43fb7a86f0d69637c3734d3b7506a29b
